apiVersion: infinispan.org/v2alpha1
kind: Cache
metadata:
  name: employees
  namespace: jdg-cross-site
spec:
  clusterName: dg
  name: employees
  template: |
    replicatedCache:
      mode: "ASYNC"
      statistics: "true"
      encoding:
        key:
          mediaType: "text/plain; charset=UTF-8"
        value:
          mediaType: "application/json; charset=UTF-8"
      locking:
        isolation: "REPEATABLE_READ"
      expiration:
        lifespan: "600000"
        maxIdle: "300000"
  updates:
    strategy: retain
